<a href="https://colab.research.google.com/github/PoluSanjay/PDS-2303a51731_BT11/blob/main/lab3_b11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.random.seed(42)
scores = np.random.randint(40, 100, size=(4, 4))
print("Test Scores (4x4 matrix):\n", scores, "\n")

row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("Row-wise Means:", row_means)
print("Column-wise Means:", col_means, "\n")

std_dev = np.std(scores)
variance = np.var(scores)
print("Standard Deviation (global):", std_dev)
print("Variance (global):", variance, "\n")

global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("Global Maximum:", global_max, "at index", max_index)
print("Global Minimum:", global_min, "at index", min_index, "\n")

median_val = np.median(scores)
print("Median Value (global):", median_val)

print("\n--- Summary ---")
print(f"Average scores per row: {row_means}")
print(f"Average scores per column: {col_means}")
print(f"Overall mean score: {np.mean(scores):.2f}")
print(f"Score variability (std dev): {std_dev:.2f}")
print(f"Highest score {global_max} at position {max_index}")
print(f"Lowest score {global_min} at position {min_index}")
print(f"Median score across all students: {median_val}")


Test Scores (4x4 matrix):
 [[78 91 68 54]
 [82 47 60 78]
 [97 58 62 50]
 [50 63 92 75]] 

Row-wise Means: [72.75 66.75 66.75 70.  ]
Column-wise Means: [76.75 64.75 70.5  64.25] 

Standard Deviation (global): 15.578305227142007
Variance (global): 242.68359375 

Global Maximum: 97 at index (np.int64(2), np.int64(0))
Global Minimum: 47 at index (np.int64(1), np.int64(1)) 

Median Value (global): 65.5

--- Summary ---
Average scores per row: [72.75 66.75 66.75 70.  ]
Average scores per column: [76.75 64.75 70.5  64.25]
Overall mean score: 69.06
Score variability (std dev): 15.58
Highest score 97 at position (np.int64(2), np.int64(0))
Lowest score 47 at position (np.int64(1), np.int64(1))
Median score across all students: 65.5
